version: "3.9"

services:
  postgresDb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/PostgresData:/var/lib/postgresql/data
  
  mongoDb:
    image: mongo:latest
    container_name: mongoDb
    ports:
      - "27017:27017"
    volumes:
      - ./db/MongoData:/data/db
    restart: always